name: Run tests

on:
  push:
  pull_request:
    branches:
      - main



jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        name: Setup cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Set ENV
        run: mv .env.ci .env

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm test


  TypeScript-Static-Analyis:
    runs-on: ubuntu-latest
    name: TypeScript static analysis
    needs: Unit-Tests
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        name: Setup cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Set ENV
        run: mv .env.ci .env

      - name: Build application
        run: npm run build

      - name: Lint
        run: npm run lint

  Solidity-Static-Analysis-Solhint:
    runs-on: ubuntu-latest
    name: Solidity static analysis (Solhint)
    needs: Unit-Tests
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        name: Set up cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Set up node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci
        
      - name: Set ENV
        run: mv .env.ci .env

      - name: Build application
        run: npm run build

      - name: Lint
        run: npm run lint-sol

  Solidity-Static-Analysis-Slither:
    runs-on: ubuntu-latest
    name: Solidity static analysis (Slither)
    needs: Unit-Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        name: Set up cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Set ENV
        run: mv .env.ci .env

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install Slither
        run: pip3 install slither-analyzer

      - name: Slither Static Analysis
        run: slither . --config-file slither.json
